services:
  redis:
    image: "redis:7.2-alpine"
    container_name: redis
    command: --save 1 1 --loglevel warning --maxmemory-policy noeviction
    volumes:
      - redis-data:/data
    ports:
      - "16379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - hub-network

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: replicator
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hub-network

  replicator:
    build: .
    container_name: replicator
    command: npm start
    environment:
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/replicator
      - POSTGRES_MAX_POOL=50
      - HUB_HOST=api.farcasthub.com:2283
      - REDIS_URL=redis:6379
    depends_on:
      - redis
      - postgres
    networks:
      - hub-network

volumes:
  redis-data:
  postgres-data:

networks:
  hub-network:
    name: hub-network
    driver: bridge
